### ISSUE TITLE
UTF8

### ISSUE THREAD

**Issue by pinkladywithcoco** [json5/json5-dotnet#5]
Does this lib support utf8 ??

**Comment by jordanbtucker** [comment]
Yes, the `JSON5Parser` constructor accepts a [`TextReader`](https://msdn.microsoft.com/en-us/library/system.io.textreader(v=vs.110).aspx), so you could do the following.

```c#
var reader = new StreamReader(@"C:\test.json", Encoding.UTF8);
var parser = new JSON5Parser(reader);
```
